openapi: 3.0.3
info:
  title: Сервис инвентаризации RenovaTech
  version: 0.0.2
servers:
- description: Dev Server
  url: http://localhost:8080/api/v1
paths:
  /tools:
    get:
      summary: Метод получения списка инструментов
      tags:
        - Tools
      operationId: getAllTools
      responses:
        "200":
          description: Успешный ответ со списком инструментов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tools'
        default:
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tools/{tool_id}:
    get:
      summary: Метод получения инструмента по идентификатору
      tags:
        - Tools
      operationId: getToolById
      parameters:
        - name: tool_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
    
      responses:
        "200":
          description: Успешный ответ со списком инструментов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
        default:
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
components:
  schemas:
    Tool:
      type: object
      required:
        - name
        - status      
      properties:
        tool_id:
          type: integer
          example: 1
        name:
          type: string
          example: Шуруповерт Макита
        status:
          type: string
          example: Новый
          description: Состояние инструмента
    Tools:
      type: array
      items:
        $ref: '#/components/schemas/Tool'
    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
        message:
          type: string
      example:
        code: 0
        message: message

      
      
